# Generated by Django 4.0.1 on 2022-03-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_gpu_specs_alter_products_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.gpu_specs'),
        ),
    ]
