# Generated by Django 4.0.1 on 2022-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_products_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
