# Generated by Django 4.0.1 on 2022-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
