# Generated by Django 4.0.1 on 2022-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Price',
        ),
    ]
